### ISSUE TITLE
ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {"<class 'numpy.ndarray'>"}), (<class 'list'> containing values of types {"<class 'int'>"})

### ISSUE THREAD

**Issue by AgnesElza** [geekSiddharth/DeepCoherence#3]
How to solve this problem?
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    callbacks=[checkpoints])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1064, in fit
    steps_per_execution=self._steps_per_execution)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1099, in __init__
    adapter_cls = select_data_adapter(x, y)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 964, in select_data_adapter
    _type_name(x), _type_name(y)))
ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {"<class 'numpy.ndarray'>"}), (<class 'list'> containing values of types {"<class 'int'>"})
[ ]

**Comment by F1y1113** [comment]
I met the same problem, looking forward to a solution.
